export default {
    dialplan_type: [{
        label: 'Condition or Regex',
        options: [
            {value: "context", label: "Context"},
            {value: "username", label: "Username"},
            {value: "rdnis", label: "RDNIS"},
            {value: "destination_number", label: "Destination Number"},
            {value: "dialplan", label: "Dialplan"},
            {value: "caller_id_name", label: "Caller ID Name"},
            {value: "caller_id_number", label: "Caller ID Number"},
            {value: "ani", label: "ANI"},
            {value: "ani2", label: "ANI2"},
            {value: "uuid", label: "UUID"},
            {value: "source", label: "Source"},
            {value: "chan_name", label: "Channel Name"},
            {value: "network_addr", label: "Network Address"},
            {value: "${number_alias}", label: "${number_alias}"},
            {value: "${sip_from_uri}", label: "${sip_from_uri}"},
            {value: "${sip_from_user}", label: "${sip_from_user}"},
            {value: "${sip_from_host}", label: "${sip_from_host}"},
            {value: "${sip_contact_uri}", label: "${sip_contact_uri}"},
            {value: "${sip_contact_user}", label: "${sip_contact_user}"},
            {value: "${sip_contact_host}", label: "${sip_contact_host}"},
            {value: "${sip_to_uri}", label: "${sip_to_uri}"},
            {value: "${sip_to_user}", label: "${sip_to_user}"},
            {value: "${sip_to_host}", label: "${sip_to_host}"},
            {value: "${toll_allow}", label: "${toll_allow}"},
            {value: "${sip_h_Diversion}", label: "${sip_h_Diversion}"},
        ]
    },
    {
        label: 'Applications',
        options: [
            {value: "acknowledge_call", label: "acknowledge_call"},
            {value: "answer", label: "answer"},
            {value: "att_xfer", label: "att_xfer"},
            {value: "avmd", label: "avmd"},
            {value: "avmd_start", label: "avmd_start"},
            {value: "avmd_stop", label: "avmd_stop"},
            {value: "bgsystem", label: "bgsystem"},
            {value: "bind_digit_action", label: "bind_digit_action"},
            {value: "bind_meta_app", label: "bind_meta_app"},
            {value: "block_dtmf", label: "block_dtmf"},
            {value: "break", label: "break"},
            {value: "bridge", label: "bridge"},
            {value: "bridge_export", label: "bridge_export"},
            {value: "broadcast", label: "broadcast"},
            {value: "callcenter", label: "callcenter"},
            {value: "callcenter_track", label: "callcenter_track"},
            {value: "capture", label: "capture"},
            {value: "capture_text", label: "capture_text"},
            {value: "check_acl", label: "check_acl"},
            {value: "clear_digit_action", label: "clear_digit_action"},
            {value: "clear_speech_cache", label: "clear_speech_cache"},
            {value: "cng_plc", label: "cng_plc"},
            {value: "conference", label: "conference"},
            {
                value: "conference_set_auto_outcall",
                label: "conference_set_auto_outcall"
            },
            {value: "curl", label: "curl"},
            {value: "curl_sendfile", label: "curl_sendfile"},
            {value: "db", label: "db"},
            {value: "debug_media", label: "debug_media"},
            {value: "decode_video", label: "decode_video"},
            {value: "deduplicate_dtmf", label: "deduplicate_dtmf"},
            {value: "deflect", label: "deflect"},
            {value: "delay_echo", label: "delay_echo"},
            {value: "detect_audio", label: "detect_audio"},
            {value: "detect_silence", label: "detect_silence"},
            {value: "detect_speech", label: "detect_speech"},
            {
                value: "digit_action_set_realm",
                label: "digit_action_set_realm"
            },
            {value: "displace_session", label: "displace_session"},
            {value: "early_hangup", label: "early_hangup"},
            {value: "eavesdrop", label: "eavesdrop"},
            {value: "echo", label: "echo"},
            {value: "enable_heartbeat", label: "enable_heartbeat"},
            {value: "enable_keepalive", label: "enable_keepalive"},
            {value: "endless_playback", label: "endless_playback"},
            {value: "enum", label: "enum"},
            {value: "eval", label: "eval"},
            {value: "event", label: "event"},
            {value: "execute_extension", label: "execute_extension"},
            {value: "export", label: "export"},
            {value: "fax_detect", label: "fax_detect"},
            {value: "fifo", label: "fifo"},
            {value: "fifo_track_call", label: "fifo_track_call"},
            {value: "filter_codecs", label: "filter_codecs"},
            {value: "final", label: "final"},
            {value: "fire", label: "fire"},
            {value: "flush_dtmf", label: "flush_dtmf"},
            {value: "gentones", label: "gentones"},
            {value: "group", label: "group"},
            {value: "hangup", label: "hangup"},
            {value: "hash", label: "hash"},
            {value: "hold", label: "hold"},
            {value: "info", label: "info"},
            {value: "info", label: "info"},
            {value: "intercept", label: "intercept"},
            {value: "ivr", label: "ivr"},
            {value: "jitterbuffer", label: "jitterbuffer"},
            {value: "limit", label: "limit"},
            {value: "limit_execute", label: "limit_execute"},
            {value: "limit_hash", label: "limit_hash"},
            {value: "limit_hash_execute", label: "limit_hash_execute"},
            {value: "log", label: "log"},
            {value: "loop_playback", label: "loop_playback"},
            {value: "lua", label: "lua"},
            {value: "lua", label: "lua"},
            {value: "media_reset", label: "media_reset"},
            {value: "mkdir", label: "mkdir"},
            {value: "msrp_recv_file", label: "msrp_recv_file"},
            {value: "msrp_send_file", label: "msrp_send_file"},
            {value: "multiset", label: "multiset"},
            {value: "multiunset", label: "multiunset"},
            {value: "mutex", label: "mutex"},
            {value: "native_eavesdrop", label: "native_eavesdrop"},
            {value: "novideo", label: "novideo"},
            {value: "park", label: "park"},
            {value: "park_state", label: "park_state"},
            {value: "phrase", label: "phrase"},
            {value: "pickup", label: "pickup"},
            {
                value: "play_and_detect_speech",
                label: "play_and_detect_speech"
            },
            {value: "play_and_get_digits", label: "play_and_get_digits"},
            {value: "play_fsv", label: "play_fsv"},
            {value: "play_yuv", label: "play_yuv"},
            {value: "playback", label: "playback"},
            {value: "pre_answer", label: "pre_answer"},
            {value: "preprocess", label: "preprocess"},
            {value: "presence", label: "presence"},
            {value: "privacy", label: "privacy"},
            {value: "push", label: "push"},
            {value: "queue_dtmf", label: "queue_dtmf"},
            {value: "read", label: "read"},
            {value: "record", label: "record"},
            {value: "record_fsv", label: "record_fsv"},
            {value: "record_session", label: "record_session"},
            {value: "record_session_mask", label: "record_session_mask"},
            {value: "record_session_pause", label: "record_session_pause"},
            {value: "record_session_resume", label: "record_session_resume"},
            {value: "record_session_unmask", label: "record_session_unmask"},
            {value: "recovery_refresh", label: "recovery_refresh"},
            {value: "redirect", label: "redirect"},
            {value: "remove_bugs", label: "remove_bugs"},
            {value: "rename", label: "rename"},
            {value: "reply", label: "reply"},
            {value: "respond", label: "respond"},
            {value: "reuse_caller_profile", label: "reuse_caller_profile"},
            {value: "ring_ready", label: "ring_ready"},
            {value: "rxfax", label: "rxfax"},
            {value: "say", label: "say"},
            {value: "sched_broadcast", label: "sched_broadcast"},
            {value: "sched_cancel", label: "sched_cancel"},
            {value: "sched_hangup", label: "sched_hangup"},
            {value: "sched_heartbeat", label: "sched_heartbeat"},
            {value: "sched_transfer", label: "sched_transfer"},
            {value: "send", label: "send"},
            {value: "send_display", label: "send_display"},
            {value: "send_dtmf", label: "send_dtmf"},
            {value: "send_info", label: "send_info"},
            {value: "session_loglevel", label: "session_loglevel"},
            {value: "set", label: "set"},
            {value: "set", label: "set"},
            {value: "set_audio_level", label: "set_audio_level"},
            {value: "set_global", label: "set_global"},
            {value: "set_media_stats", label: "set_media_stats"},
            {value: "set_mute", label: "set_mute"},
            {value: "set_name", label: "set_name"},
            {value: "set_profile_var", label: "set_profile_var"},
            {value: "set_user", label: "set_user"},
            {value: "set_zombie_exec", label: "set_zombie_exec"},
            {value: "sleep", label: "sleep"},
            {value: "socket", label: "socket"},
            {value: "sofia_sla", label: "sofia_sla"},
            {
                value: "sofia_stir_shaken_vs",
                label: "sofia_stir_shaken_vs"
            },
            {value: "soft_hold", label: "soft_hold"},
            {value: "sound_test", label: "sound_test"},
            {value: "spandsp_detect_tdd", label: "spandsp_detect_tdd"},
            {value: "spandsp_inject_tdd", label: "spandsp_inject_tdd"},
            {value: "spandsp_send_tdd", label: "spandsp_send_tdd"},
            {value: "spandsp_start_dtmf", label: "spandsp_start_dtmf"},
            {
                value: "spandsp_start_fax_detect",
                label: "spandsp_start_fax_detect"
            },
            {
                value: "spandsp_start_tone_detect",
                label: "spandsp_start_tone_detect"
            },
            {
                value: "spandsp_stop_detect_tdd",
                label: "spandsp_stop_detect_tdd"
            },
            {value: "spandsp_stop_dtmf", label: "spandsp_stop_dtmf"},
            {
                value: "spandsp_stop_fax_detect",
                label: "spandsp_stop_fax_detect"
            },
            {
                value: "spandsp_stop_inject_tdd",
                label: "spandsp_stop_inject_tdd"
            },
            {
                value: "spandsp_stop_tone_detect",
                label: "spandsp_stop_tone_detect"
            },
            {value: "speak", label: "speak"},
            {value: "start_dtmf", label: "start_dtmf"},
            {value: "start_dtmf_generate", label: "start_dtmf_generate"},
            {value: "stop", label: "stop"},
            {value: "stop", label: "stop"},
            {value: "stop_displace_session", label: "stop_displace_session"},
            {value: "stop_dtmf", label: "stop_dtmf"},
            {value: "stop_dtmf_generate", label: "stop_dtmf_generate"},
            {value: "stop_record_session", label: "stop_record_session"},
            {value: "stop_tone_detect", label: "stop_tone_detect"},
            {
                value: "stop_video_write_overlay",
                label: "stop_video_write_overlay"
            },
            {value: "stopfax", label: "stopfax"},
            {value: "strftime", label: "strftime"},
            {value: "t38_gateway", label: "t38_gateway"},
            {value: "three_way", label: "three_way"},
            {value: "tone_detect", label: "tone_detect"},
            {value: "transfer", label: "transfer"},
            {value: "transfer_vars", label: "transfer_vars"},
            {value: "txfax", label: "txfax"},
            {value: "unbind_meta_app", label: "unbind_meta_app"},
            {value: "unblock_dtmf", label: "unblock_dtmf"},
            {value: "unhold", label: "unhold"},
            {value: "unloop", label: "unloop"},
            {value: "unset", label: "unset"},
            {value: "unset", label: "unset"},
            {value: "unshift", label: "unshift"},
            {value: "vad_test", label: "vad_test"},
            {value: "valet_park", label: "valet_park"},
            {value: "verbose_events", label: "verbose_events"},
            {value: "video_decode", label: "video_decode"},
            {value: "video_refresh", label: "video_refresh"},
            {value: "video_write_overlay", label: "video_write_overlay"},
            {value: "wait_for_answer", label: "wait_for_answer"},
            {value: "wait_for_silence", label: "wait_for_silence"},
            {
                value: "wait_for_video_ready",
                label: "wait_for_video_ready"
            },
        ]
    }]
}